param(
    [Parameter(Mandatory = $true)]
    [string]$CounterFile,

    [Parameter(Mandatory = $true)]
    [string]$OutputFile
)

$ErrorActionPreference = "Stop"

$counterDirectory = Split-Path -Parent $CounterFile
if (-not [string]::IsNullOrWhiteSpace($counterDirectory)) {
    New-Item -ItemType Directory -Force -Path $counterDirectory | Out-Null
}

$buildNumber = 0
if (Test-Path -LiteralPath $CounterFile) {
    $raw = (Get-Content -LiteralPath $CounterFile -Raw).Trim()
    if ($raw -match "^\d+$") {
        $buildNumber = [int]$raw
    }
}

$buildNumber += 1
Set-Content -LiteralPath $CounterFile -Value $buildNumber -NoNewline -Encoding ASCII

$versionDate = Get-Date -Format "ddMMyy"
$version = "${versionDate}b${buildNumber}"

$outputDirectory = Split-Path -Parent $OutputFile
if (-not [string]::IsNullOrWhiteSpace($outputDirectory)) {
    New-Item -ItemType Directory -Force -Path $outputDirectory | Out-Null
}

$content = @"
// <auto-generated />
namespace YellowFox.Desktop;

internal static class YellowFoxBuildInfo
{
    public const int BuildNumber = $buildNumber;
    public const string Version = "$version";
}
"@

Set-Content -LiteralPath $OutputFile -Value $content -Encoding UTF8
